language: php
php:
  - 8.0
  - 8.1

services: mysql

before_script:
    - composer install --dev
    - mysql -e 'CREATE DATABASE test;'

script:
    - ./vendor/bin/tester src
    - ./vendor/bin/phpstan analyse src -l 8