language: php
php:
  - 7.1
  - 7.2
  - 7.3

services: mysql

before_script:
    - composer install --dev
    - mysql -e 'CREATE DATABASE test;'

script: ./vendor/phpunit/phpunit/phpunit --configuration phpunit.xml